apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mn6r7zjzv-nodejs-gitops
  description: This is GitOps manifest for mn6r7zjzv-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=mn6r7zjzv-nodejs
    backstage.io/kubernetes-id: mn6r7zjzv-nodejs 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-rhdh-qe/mn6r7zjzv-nodejs-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:mn6r7zjzv-nodejs
