apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mn6r7zjzv-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mn6r7zjzv-nodejs 
  name: mn6r7zjzv-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mn6r7zjzv-nodejs 
